version: '3.8'

services:
  app:
    container_name: node-docker
    restart: always
    build: .
    ports:
      - '8080:8000'
    external_links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'
